import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
      variables: {
        colorPrimary: "#FFFFFF",
        fontSize: "16px",
      },
    }}>
      <html lang="en">
        <body
          className={`antialiased body h-screen`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
